site_name: Windsor CLI
docs_dir: docs

site_url: https://tvangundy.github.io/pages-test/

nav:
  - 'Home': index.md
  - 'Test': test/README.md

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

repo_url: https://github.com/windsor-hotel/cli.git

# plugins:
#   - versioning
#   - encryptcontent:
#       global_password: 'letsbuildit'
