site_name: Windsor CLI

site_url: https://tvangundy.github.io/pages-test.github.io/
repo_url: https://github.com/tvangundy/pages-test.github.io

nav:
  - 'Home': index.html
  - 'Test': test/README.md

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


# plugins:
#   - versioning
#   - encryptcontent:
#       global_password: 'letsbuildit'
